In [72]:
import pandas as pd
import numpy as np

#mengambil data

df = pd.read_csv('data-stroke.csv')
df.head()

Umur  Hipertensi  Penyakit Jantung  Pernah Menikah  Tempat Tinggal  \
0  67.0           0                 1               1               1   
1  61.0           0                 0               1               0   
2  80.0           0                 1               1               0   
3  49.0           0                 0               1               1   
4  79.0           1                 0               1               0   

   Rata-rata Kadar Glukoasa   bmi  Strok   Status Merokok  
0                    228.69  36.6      1  formerly smoked  
1                    202.21   NaN      1     never smoked  
2                    105.92  32.5      1     never smoked  
3                    171.23  34.4      1           smokes  
4                    174.12  24.0      1     never smoked

In [57]:
# Melihat dimensi atau ukuran data

N, D = df.shape
print('N: %d, D: %d' %(N, D))

N: 5110, D: 9


In [58]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df, df, test_size=0.2, random_state=0)
print(x_train.shape, y_train.shape)

(4088, 9) (4088, 9)


In [59]:
print(x_test.shape, y_test.shape)

(1022, 9) (1022, 9)


In [60]:
print(x_train)

      Umur  Hipertensi  Penyakit Jantung  Pernah Menikah  Tempat Tinggal  \
3029  36.0           0                 0               1               0   
2277  34.0           0                 0               1               0   
3002  60.0           0                 0               1               0   
246   75.0           0                 0               1               0   
2825  76.0           0                 0               1               1   
...    ...         ...               ...             ...             ...   
4931  53.0           1                 0               1               0   
3264  61.0           0                 0               1               0   
1653  44.0           0                 0               1               0   
2607  21.0           0                 0               0               1   
2732  58.0           1                 0               1               0   

      Rata-rata Kadar Glukoasa   bmi  strok   Status Merokok  
3029                    

In [61]:
# proses normalisasi supaya data lebih bagus
# gunakan normalisasi minimax

from sklearn.preprocessing import MinMaxScaler
x_train1 = MinMaxScaler().fit_transform(x_train1)
x_test1 = MinMaxScaler().fit_transform(x_test1)
print(x_train1)
print(x_test1)

[[0.43847656 0.         0.         ... 0.05618133 0.3024055  0.        ]
 [0.4140625  0.         0.         ... 0.13115132 0.43757159 0.        ]
 [0.73144531 0.         0.         ... 0.04634844 0.23482245 0.        ]
 ...
 [0.53613281 0.         0.         ... 0.18276244 0.20733104 0.        ]
 [0.25537109 0.         0.         ... 0.30385006 0.22222222 0.        ]
 [0.70703125 1.         0.         ... 0.02031207 0.26231386 0.        ]]
[[1.         0.         1.         ... 0.4222421  0.2960373  1.        ]
 [0.04692082 0.         0.         ... 0.2401243  0.06993007 0.        ]
 [0.70674487 0.         0.         ... 0.11643674 0.28438228 0.        ]
 ...
 [0.63343109 0.         0.         ... 0.06662272 0.52447552 0.        ]
 [0.95112414 0.         0.         ... 0.85940958        nan 1.        ]
 [0.4257087  0.         0.         ... 0.13206836 0.14219114 0.        ]]


In [62]:
# memisahkan data fitur dan data label

x_train1 = x_train.values
x_train1 = np.delete(x_train1, 8, axis = 1)
y_train1 = x_train['Status Merokok'].values
print(x_train1.shape)
print(x_train1)

(4088, 8)
[[36.0 0 0 ... 67.29 36.7 0]
 [34.0 0 0 ... 83.53 48.5 0]
 [60.0 0 0 ... 65.16 30.8 0]
 ...
 [44.0 0 0 ... 94.71 28.4 0]
 [21.0 0 0 ... 120.94 29.7 0]
 [58.0 1 0 ... 59.52 33.2 0]]


In [63]:
# memisahkan data fitur dan label untuk data tes

x_test1 = x_test.values
x_test1 = np.delete(x_test1, 8, axis = 1)
y_test1 = x_test['Status Merokok'].values
print(x_test1.shape)
print(x_test1)

(1022, 8)
[[82.0 0 1 ... 144.9 26.4 1]
 [4.0 0 0 ... 106.22 16.7 0]
 [58.0 0 0 ... 79.95 25.9 0]
 ...
 [52.0 0 0 ... 69.37 36.2 0]
 [78.0 0 0 ... 237.75 nan 1]
 [35.0 0 0 ... 83.27 19.8 0]]


In [64]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
print(x.shape)

(5110, 8)


In [65]:
# Proses klarifikasi dengan neural network

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
x, y = make_classification(n_samples=100, random_state=1)
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y,random_state=1)
clf = MLPClassifier(random_state=1, max_iter=300).fit(x_train, y_train)
# Melakukan Prediksi dan nilai akurasi
clf.predict_proba(x_test[:1])
clf.predict(x_test[:5, :])
clf.score(x_test, y_test)

0.88