In [112]:
import pandas as pd
import numpy as np

df = pd.read_csv('data-stroke.csv')

# Memisahkan dataset kedalam dua variabel

x_train = df.values
x_train = np.delete(x_train, 9, axis = 1)

y_train = df['smoking_status'].values

df.head()

age  hypertension  heart_disease ever_married      work_type  \
0  67.0             0              1          Yes        Private   
1  61.0             0              0          Yes  Self-employed   
2  80.0             0              1          Yes        Private   
3  49.0             0              0          Yes        Private   
4  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level   bmi  stroke   smoking_status  
0          Urban             228.69  36.6       1  formerly smoked  
1          Rural             202.21   NaN       1     never smoked  
2          Rural             105.92  32.5       1     never smoked  
3          Urban             171.23  34.4       1           smokes  
4          Rural             174.12  24.0       1     never smoked

In [113]:
# Memasukan data Uji

df = pd.read_csv('data-uji.csv')

x_test = df.values
x_test = np.delete(x_test, 9, axis = 1)

y_test = df['smoking_status'].values
print(x_test)
df.head()

[[67.0 0 1 ... 228.69 36.6 1]
 [61.0 0 0 ... 202.21 nan 1]
 [80.0 0 1 ... 105.92 32.5 1]
 ...
 [35.0 0 0 ... 82.99 30.6 0]
 [51.0 0 0 ... 166.29 25.6 0]
 [44.0 0 0 ... 85.28 26.2 0]]


age  hypertension  heart_disease ever_married      work_type  \
0  67.0             0              1          Yes        Private   
1  61.0             0              0          Yes  Self-employed   
2  80.0             0              1          Yes        Private   
3  49.0             0              0          Yes        Private   
4  79.0             1              0          Yes  Self-employed   

  Residence_type  avg_glucose_level   bmi  stroke   smoking_status  
0          Urban             228.69  36.6       1  formerly smoked  
1          Rural             202.21   NaN       1     never smoked  
2          Rural             105.92  32.5       1     never smoked  
3          Urban             171.23  34.4       1           smokes  
4          Rural             174.12  24.0       1     never smoked

In [114]:
from sklearn import preprocessing

#merubah tipe data dengan menggunakan preprocessing
le = preprocessing.LabelEncoder()
df['ever_married'] = le.fit_transform(df['ever_married'])
df['work_type'] = le.fit_transform(df['work_type'])
df['Residence_type'] = le.fit_transform(df['Residence_type'])
df['smoking_status'] = le.fit_transform(df['smoking_status'])
df.head()

age  hypertension  heart_disease  ever_married  work_type  Residence_type  \
0  67.0             0              1             1          2               1   
1  61.0             0              0             1          3               0   
2  80.0             0              1             1          2               0   
3  49.0             0              0             1          2               1   
4  79.0             1              0             1          3               0   

   avg_glucose_level   bmi  stroke  smoking_status  
0             228.69  36.6       1               1  
1             202.21   NaN       1               2  
2             105.92  32.5       1               2  
3             171.23  34.4       1               3  
4             174.12  24.0       1               2

In [115]:

from sklearn.preprocessing import MinMaxScaler

x_train = MinMaxScaler().fit_transform(x_train)
x_test = MinMaxScaler().fit_transform(x_test)


ValueError: could not convert string to float: 'Yes'

In [ ]:
print(x_test)

In [ ]:
from sklearn.neural_network import MLPClassifier

cif = MLPClassifier(hidden_layer_sizes=(100,), learning_rate_init=0.1, max_iter=100)

cif.fit(x_train, y_train)